
[[dependencies]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[dependencies]]
  branch = "master"
  name = "github.com/future-architect/vuls"

[[dependencies]]
  branch = "master"
  name = "github.com/k0kubun/pp"

[[dependencies]]
  branch = "master"
  name = "github.com/kotakanbe/logrus-prefixed-formatter"

[[dependencies]]
  branch = "master"
  name = "github.com/ymomoi/goval-parser"
